name: Lint and Validate

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  powershell:
    name: PowerShell Script Analysis
    if: ${{ ! startsWith(github.head_ref, 'release-please--branches--') }}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Run PSScriptAnalyzer
      uses: microsoft/psscriptanalyzer-action@v1.1
      with:
        path: ./scripts/windows
        recurse: true
        output: results.sarif
        ignorePattern: '\.git|\.github'

    - name: Upload PSScriptAnalyzer results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: results.sarif

  shellcheck:
    name: Shell Script Analysis
    if: ${{ ! startsWith(github.head_ref, 'release-please--branches--') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts'
        ignore_paths: 'scripts/windows'
        severity: warning

  markdown:
    name: Markdown Lint
    if: ${{ ! startsWith(github.head_ref, 'release-please--branches--') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: |
          **/*.md
          !node_modules/**
          !CHANGELOG.md

  json-yaml:
    name: JSON/YAML Validation
    if: ${{ ! startsWith(github.head_ref, 'release-please--branches--') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Validate JSON files
      run: |
        find . -name "*.json" -type f -not -path "./node_modules/*" | while read file; do
          echo "Validating $file"
          python -m json.tool "$file" > /dev/null || exit 1
        done
        echo "All JSON files are valid"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Validate YAML files
      run: |
        pip install pyyaml
        find . -name "*.yml" -o -name "*.yaml" -type f -not -path "./node_modules/*" | while read file; do
          echo "Validating $file"
          python -c "import yaml; yaml.safe_load(open('$file'))" || exit 1
        done
        echo "All YAML files are valid"

  security:
    name: Security Scan
    if: ${{ ! startsWith(github.head_ref, 'release-please--branches--') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Run Trivy security scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
